# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: La petite bête qui pique | entreprise de traitement des nuisibles
email: celinewambst5067@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.la-petite-bete-qui-pique.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

image:
  path: /assets/images/opengraph.jpeg
  #height: 100
  #width: 100
  alt: Facebook logo



pages_mentions:
  adresse_site: https://www.la-petite-bete-qui-pique.fr
  raison_sociale: La petite bête qui pique
  nom_entreprise: La petite bête qui pique
  responsable_donnees_personnelles: XXX
  capital_social: 3 000€
  tva_intra: FR86984730283
  siren: 984730283
  adresse_entreprise: 10 route de la carriere
  zip_code_entreprise: 50210
  ville_entreprise: Savigny
  tel_entreprise: +33669515950
  mail_entreprise: celinewambst5067@gmail.com
  nom_site: la-petite-bete-qui-pique.fr.fr
  directeur_publication: La petite bête qui pique
  hebergeur_name: netlify
  hebergeur_site : https://www.netlify.com
  hebergeur_adresse: sise 610 22nd Street, Suite 315 – CA 94107 San Francisco +1 (844) 899-7312

  editeur_site: weddoz SAS





# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
